POST http://localhost:3333/events
Content-Type: application/json

{
    "title": 123,
    "details": "Um evento para quem é louco",
    "maximumAttendees": 5
}

###

POST http://localhost:3333/events/a6b02d4d-58d8-4e5e-80be-00a8a5efea1f/attendees
Content-Type: application/json

{
    "name": "bruno ricardo",
    "email": "bruno@hotmail.com"
}

###

GET http://localhost:3333/events/a6b02d4d-58d8-4e5e-80be-00a8a5efea1f

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in